-- Add Duro frame type with sizes and prices
-- NOTE:
-- This app must start with NO prefilled stock data.
-- Users will add frame stock manually from Stock -> Frame Sizes.
-- (Kept this migration file so migration ordering remains stable.)
